name: Favorite country list

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}--runApp--${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-key: |
            ${{ runner.os }}--runApp--
            ${{ runner.os }}-- 

      - name: Install packages
        run: yarn install

      # - name: Run tests
      #   run: yarn run test

      - name: Linting
        run: yarn run lint

      - name: Building
        run: yarn run build

      